[[pages]]
name = "Naviation"
icon = "ğŸ‡²ğŸ‡²"
is_section = true

[[pages]]
path = "C:/Users/May/.streamlit/aboutus.toml"
name = "About Us!"
icon = "ğŸ«‚"

[[pages]]
path = "C:/Users/May/test2.py"
name = "**Intermediate Level Grammar & Spelling Checker**"
icon = "ğŸ”"

