[[pages]]
name = "Naviation"
icon = "ğŸ‡²ğŸ‡²"
is_section = true

[[pages]]
path = ".streamlit/aboutus.toml"
name = "About Us!"
icon = "ğŸ«‚"

[[pages]]
path = "test2.py"
name = "**Intermediate Level Grammar & Spelling Checker**"
icon = "ğŸ”"

[[pages]]
path = ".streamlit/reference.py"
name = "Our Appreciation!"
icon = "ğŸ“"